import { CODE_ICON_PATTERN } from "./iconPattern";

export const teamMembers = [
  {
    id: 1,
    name: "Lovish Jaiswal",
    title: "Frontend Developer",
    role: "Tech",
    handle: "Lovish",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Lovish.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Tech",
      bio: "My passion is Web development, building AI/ML models and problem-solving. I thrive on diving into complex topics, analyzing vast data, and connecting disparate concepts.",
      skills: "Development, Operations",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: 2,
    name: "Nidhi Singh",
    title: "Social Media Designer",
    role: "Media",
    handle: "Nidhi",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Nidhi.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Media",
      bio: "Creative designer with a passion for social media and visual storytelling. Expert in creating engaging content that resonates with audiences.",
      skills: "Design, Social Media, Content Creation",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: 3,
    name: "Anurag",
    title: "App Developer",
    role: "Tech",
    handle: "Anurag",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Anurag.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Tech",
      bio: "Mobile app development specialist focusing on creating seamless user experiences. Skilled in both iOS and Android development.",
      skills: "Mobile Development, UI/UX, Cross-platform",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: 4,
    name: "Sanya Sahu",
    title: "Frontend Developer",
    role: "Tech",
    handle: "Sanya",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Sanya.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Tech",
      bio: "Frontend specialist with expertise in modern web technologies. Passionate about creating intuitive and responsive user interfaces.",
      skills: "Frontend Development, React, UI Design",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: 5,
    name: "Varsha K N",
    title: "Team Manager",
    role: "Manager",
    handle: "Varsha",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Varsha.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Manager",
      bio: "Experienced team leader with a focus on agile methodologies and team development. Skilled in project management and team coordination.",
      skills: "Team Management, Project Planning, Leadership",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: 6,
    name: "Ankur Pathak",
    title: "Senior Manager",
    role: "Manager",
    handle: "Ankur",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Ankur.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Manager",
      bio: "Strategic leader with extensive experience in managing tech teams. Focused on innovation and organizational growth.",
      skills: "Strategic Planning, Team Leadership, Innovation Management",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: 7,
    name: "Suparn",
    title: "Senior Manager",
    role: "Manager",
    handle: "Suparn",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Suparn.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Manager",
      bio: "Experienced leader specializing in technology strategy and team development. Driven by innovation and continuous improvement.",
      skills: "Technology Strategy, Team Development, Process Optimization",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: 8,
    name: "Bharat G P",
    title: "Senior Developer",
    role: "Tech",
    handle: "Bharat",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Bharat.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Tech",
      bio: "Senior developer with expertise in full-stack development. Passionate about creating scalable and efficient solutions.",
      skills: "Full-stack Development, System Architecture, Cloud Technologies",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: 9,
    name: "Raghavendra Hande",
    title: "Senior App Developer",
    role: "Tech",
    handle: "Raghavendra",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Raghavendra.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Tech",
      bio: "Senior mobile developer specializing in native app development. Expert in creating high-performance mobile applications.",
      skills:
        "Mobile Architecture, Performance Optimization, Native Development",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
  {
    id: 10,
    name: "Mohammed Sufyan B",
    title: "Social Media Manager",
    role: "Media",
    handle: "Sufyan",
    status: "Active",
    avatarUrl: "/src/utils/MemberImages/Sufyan.png",
    iconUrl: CODE_ICON_PATTERN,
    batch: "Batch 1",
    memberDetails: {
      dateJoined: "23/10/2025",
      role: "Media",
      bio: "Social media strategist with expertise in digital marketing and content management. Focused on building engaging online communities.",
      skills: "Social Media Strategy, Content Management, Digital Marketing",
      portfolio: "https://portfolio-example.vercel.app/",
      linkedin: "https://www.linkedin.com/in/example",
      github: "https://github.com/example",
    },
  },
];
